version: "3"
services:
  api:
    build: .
    ports:
      - "3333:3333"
    command:
      - yarn
      - start
    depends_on:
      - db
      - redis
  db:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: appfood
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: app_food
  redis:
    image: redis
volumes:
  dbdata: null
